# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-15 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='decription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
